name: Run Script from Another Repository

on:
  push:
    branches:
      - master

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository 1
        uses: actions/checkout@v2
        with:
          repository: Raj-inventyv/sh_repo # Replace with the repository containing the script
          ref: main  # Replace with the branch or tag containing the script

      - name: Execute Script
        run: bash script.sh  # Replace with the name of your script file
